# Continuing interactivity in Python with the viz engine bqplot

Make sure you have installed this via the install script `test_imports_week01.ipynb` in week 1.  You may have to restart your jupyter or your browswer.

We'll start by using `bqplot` in a Grammar of Graphics & *Declaritive* sort of way, and then, if we have time, spend a few moments looking at its `matplotlib`-like interface as well which is an *Imperative* method.

In [3]:
import bqplot
import numpy as np
import ipywidgets

Now we are going to mess around with some of the declaritive programming type options that bqplot can use.  This will rely heavily on the "Grammar of Graphics" constructs.

## Random line plot with Pan/Zoom interaction

We'll now go through the example I put up on the slides for this week. 

**Data:** Let's first start by creating *data* elements for our graphic just some random numbers:

In [4]:
x = np.arange(100) # integers 0->999
y = np.random.random(100) + 5 # random numbers with mean = 5

In [5]:
x, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([5.77545088, 5.96652935, 5.64366653, 5.82329259, 5.69054326,
        5.13806036, 5.99327889, 5.74878188, 5.72275293, 5.27035593,
        5.4684503 , 5.10494478, 5.47033904, 5.09674501, 5.83561794,
        5.34797064, 5.34164572, 5.94323293, 5.20807556, 5.00758997,
        5.25275936, 5.18849284, 5.25639907, 5.85335773, 5.82864524,
        5.55409666, 5.38988247, 5.94411078, 5.83748627, 5.46431553,
        5.11351624, 5.10847166, 5.24028184, 5.43712448, 5.0005938 ,
        5.00771591, 5.05810062, 5.50739384, 5.76956929, 5.61686567,
      

**Scales:** Now we'll define some scale objects which will determine how lines will be drawn on our canvas:

In [6]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

**Marks:** Now we are going to use GoG type calls to define what lines to actually draw combining information about our data and our scales:

In [7]:
lines = bqplot.Lines(x = x, y = y, scales = {'x': x_sc, 'y': y_sc})

**Axis:** Now, we are going to define what axis we want placed around the lines that we draw we'll draw both x & y axis.

In [8]:
ax_x = bqplot.Axis(scale = x_sc, label = 'X Value')
ax_y = bqplot.Axis(scale = y_sc, label = 'Y Value', orientation = 'vertical')

**Figure:** Finally, we combine all these things together into a bonified figure:

In [9]:
fig = bqplot.Figure(marks = [lines], axes = [ax_x, ax_y])
#display(fig) # you might also want to try "display"
# if you don't see the following fig, here is where
#  you might have to close and reopen your notebook
fig # note: just "fig" instead of "display(fig)" may also be an option for you

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

Ok, but this isn't interactive in anyway lets make it!!  There are a few "interactions" supported in `bqplot` but not all of them are supported for all types of plots.  The docs can be a little nebulous about what plot can use what type of interaction, so we'll just try a few and see what happens.  Here, let's add in an ability to pan/zoom in our plot:

In [10]:
pz = bqplot.interacts.PanZoom( scales = {'x': [x_sc], 'y': [y_sc]})

In [11]:
fig = bqplot.Figure(marks = [lines], axes = [ax_x, ax_y], interaction = pz)
#display(fig)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

Note that if I pan and zoom, the figure updates. Ooooo. fancy.

Note also, that the above figure also reacts as well this is because we are using the same lines & ax's objects -- recall back to last week that this was a feature of using ipywidgets and traitlets as well.

### ASIDE: where things can go wrong (SKIPPING generally):

In [10]:
# lets see an example of where this can fail

# first lets make an x from 0-10 in 100 steps
x = np.mgrid[0.0:10.0:100j]
# and 2 y variables
y1 = x * 2
y2 = x**2

In [11]:
x_sc = bqplot.LinearScale(min = 1, max = 10)
# lets do one y-scale over linear and 1 over log
y_sc1 = bqplot.LinearScale(min = 1, max = 20)
y_sc2 = bqplot.LogScale(min = 1, max = 100)

In [12]:
# lets genrate lines for each y value
lines1 = bqplot.Lines(x = x, y = y1, scales = {'x': x_sc, 'y': y_sc1})
lines2 = bqplot.Lines(x = x, y = y2, scales = {'x': x_sc, 'y': y_sc2})

In [13]:
# and lets plot an x axis like before
ax_x = bqplot.Axis(scale = x_sc, label = 'X Value')
# and one y axis on the left
ax_y1 = bqplot.Axis(scale = y_sc1, label = 'Y1 Value', 
                    orientation = 'vertical')
# and one y-axis on the right
ax_y2 = bqplot.Axis(scale = y_sc2, label = 'Y2 Value', 
                    orientation = 'vertical', side = 'right')

In [14]:
# lets allow pan and zoom
pz = bqplot.interacts.PanZoom(scales = {'x': [x_sc], 
                                        'y': [y_sc1, y_sc2]})
#bqplot.interacts.PanZoom?
fig = bqplot.Figure(marks = [lines1, lines2], 
                    axes = [ax_x, ax_y1, ax_y2], interaction=pz)
#display(fig)
fig
# now we note if we zoom out too far, or pan to too negative of the x-axis
# we lose a line

# why? because the line is log-scaled, and log(numbers < 0) is undefined

# this is a way in which declaritive programming can fail because there
#  aren't obvious options to inhibit pan&zoom to a positive range

Figure(axes=[Axis(label='X Value', scale=LinearScale(max=10.0, min=1.0), side='bottom'), Axis(label='Y1 Value'…

### END ASIDE/SKIP

FYI lots of more fun notebooks here: https://github.com/dmadeka/PyGotham-2017

From video tutorial here: https://www.youtube.com/watch?v=rraXF0EjRC8

## Random Scatter plot
Ok, lets do another quick interactive example using a scatter plot:

In [15]:
# 1. Data
x = np.random.random(100) # random points betweeon 0-1
y = np.random.random(100) # random points betweeon 0-1

In [13]:
x, y

(array([0.85362526, 0.53194837, 0.39953434, 0.09666556, 0.0445231 ,
        0.23100304, 0.810035  , 0.22255122, 0.11853157, 0.80736376,
        0.38952435, 0.40417638, 0.29931082, 0.92465633, 0.86473108,
        0.44354689, 0.45636961, 0.41698903, 0.40028852, 0.68509154,
        0.67701967, 0.61855315, 0.73077927, 0.80125112, 0.23296721,
        0.54836656, 0.08153725, 0.89337502, 0.07616575, 0.0234584 ,
        0.92730506, 0.4967789 , 0.27363804, 0.54394328, 0.74822258,
        0.53536392, 0.0651771 , 0.74362808, 0.16526432, 0.90554949,
        0.94989028, 0.57108579, 0.65701428, 0.70775977, 0.31779696,
        0.46129699, 0.116873  , 0.07341928, 0.8153411 , 0.72396098,
        0.02626131, 0.82585165, 0.26598544, 0.58198774, 0.97012608,
        0.63824258, 0.27289061, 0.66789825, 0.12111153, 0.86037509,
        0.26389325, 0.19187529, 0.9335596 , 0.30535769, 0.32250042,
        0.39820889, 0.62437055, 0.66988707, 0.84795436, 0.67753447,
        0.89068745, 0.61974307, 0.45489939, 0.64

Create scales and axis like we did before:

In [14]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
x_ax = bqplot.Axis(scale = x_sc, label = 'X')
y_ax = bqplot.Axis(scale = y_sc, label = 'Y', orientation = 'vertical')

Create a scatter plot graphing object with these random x/y and scales:

In [16]:
# 4. marks
scatters = bqplot.Scatter(x = x,
                          y = y,
                          scales = {'x': x_sc, 'y': y_sc})

Now, lets create a selector to select points along the x-axis.  We will use the `bqplot` interaction called `FastIntervalSelector`:

In [17]:
# 5. interactions
selector = bqplot.interacts.FastIntervalSelector(
            scale = x_sc, marks = [scatters]) 

Let's check out the full figure + interaction!

In [18]:
# Finally: fig
fig = bqplot.Figure(marks = [scatters], axes = [x_ax, y_ax], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

This might depend on what computer you are in, but on my mac, I click to start selecting and then double click to "lock in" my selected region.

How do we tell what interval we have selected?

In [19]:
selector.selected

array([0.49528187, 0.91374002])

So, its a little hard to see what points are selected.  There are some hidden tags within our scatter plot points that we can mess with to change our our plot looks.  These have CSS styling (how HTML is styled), so they'll look very un-Pythonic, because they are!  We'll get more into this sort of thing when we are doing Javascript later in the course:

In [20]:
scatters.unselected_style={'opacity': 0.8} # when unselected, make the points a little see-through

scatters.selected_style={'fill': 'red', 'stroke': 'yellow'} # fill with red, outline in yellow when selected

Display updated figure:

In [21]:
fig = bqplot.Figure(marks = [scatters], axes = [x_ax, y_ax], interaction = selector)
#display(fig)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

## Random Heatmap with 2D data

Lets start thinking about heatmaps with some random data:

In [22]:
# 1. Data
data = np.random.random((10, 10))
data # your's may look different!

array([[0.65771209, 0.86892101, 0.75079741, 0.47831359, 0.26155098,
        0.52151869, 0.27907678, 0.53829732, 0.33304627, 0.023503  ],
       [0.88353795, 0.41370045, 0.45037387, 0.25472344, 0.26821432,
        0.44175616, 0.29519296, 0.95435813, 0.7924018 , 0.88556012],
       [0.6459481 , 0.5365875 , 0.24092927, 0.59133017, 0.31490256,
        0.96413999, 0.17960387, 0.26897582, 0.33230235, 0.53189301],
       [0.51955953, 0.79508841, 0.56310568, 0.14217045, 0.98689766,
        0.53832668, 0.8374997 , 0.43176806, 0.04720695, 0.68010954],
       [0.04892631, 0.7190729 , 0.03472731, 0.05751688, 0.53299076,
        0.25977685, 0.14191432, 0.02961739, 0.06236137, 0.1124625 ],
       [0.40157269, 0.38420189, 0.09597065, 0.71033088, 0.51774316,
        0.84195228, 0.7285728 , 0.43345603, 0.90410568, 0.24502789],
       [0.10461881, 0.10283937, 0.30794282, 0.29275377, 0.85320969,
        0.30195964, 0.27278646, 0.21424578, 0.26471926, 0.52563957],
       [0.98415323, 0.46944385, 0.8715710

So we just have a 10 x 10 array here.

Lets start by generating a quick heat map with `bqplot`'s `GridHeatMap` marks function. We've been making plots with linear scales before, but now for a heatmap, we will want to make a color scale as well.  Let's start with just assigning a color scale, and going from there:

In [24]:
# 2. Scales -- in this case, just a color scale
col_sc = bqplot.ColorScale() # use bqplot to define a color scale

# 3. Axis -- skipping for now

# 4. Mark -- use colorscale to make make heatmap of our data:
heat_map = bqplot.GridHeatMap(color = data, scales = {'color': col_sc})

# 5. Skipping any interactions

# Finally: figure
fig = bqplot.Figure(marks = [heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.65771…

There are some things we probably want to do here.  One of them being able to change the color scale -- we spent all this time thinking about color, let's put those thoughts to good use!

In [25]:
# 1. Data -- same as above

# 2. Scale -- color with new color scheme
col_sc = bqplot.ColorScale(scheme = "Reds") # color scheme of reds

# 3. skip Axis

# 4. Marks -- use colorscale to make make heatmap of our data:
heat_map = bqplot.GridHeatMap(color = data, scales = {'color': col_sc})

# Figure
fig = bqplot.Figure(marks = [heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.65771…

Let's build upon this plot by adding some axis so that we can think about how to label our data.  Currently, we *only* have a color scale for each color in our 10x10 grid, so we will label this color axis with a colorbar:

In [26]:
# 1. Data -- same

# 2. Scales -- color
col_sc = bqplot.ColorScale(scheme = "Reds")
# lets plot some axes on our plot as well, in this case
#  our axis will be a color bar, vertically on the right
#  of our heatmap

# 3. Axis (finally) -- here a "color axis" is just a colorbar
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right') 

# 4. Marks -- put it all together and lets take a look!
heat_map = bqplot.GridHeatMap(color = data, 
                              scales = {'color': col_sc})

# 5. no interactions

# generate fig!
fig = bqplot.Figure(marks = [heat_map], axes = [c_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right')], fig_margin={'t…

While our x/y bins don't mean anything in particular in this case - we are dealing with just a randomly binned 10x10 dataset after all - we none-the-less probably want to put at least the bin labels on there.  So let's make some x/y scales and some x/y axis (note I'm doing Scales/Axis a bit out of order here to group by kind of axis):

In [27]:
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

Why did I choose ordinal scales?  Well again - the bins, while numbered, don't actually mean anything, so in a sense they are "categorical" bins, and our scales should reflect that fact!

Color scale & color axis like before:

In [28]:
col_sc = bqplot.ColorScale(scheme = "Reds")

c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')

Combine all these scales, axis and the data into a heat map mark using `bqplot.GridHeatMap`:

In [30]:
# Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc})

... put these marks and axes on a figure canvas and plot it!

In [31]:
# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

So, we are almost there -- we don't have any interactivity!  Let's get into it.  In this case, we can actually specify the interaction when we are constructing the `GridHeatMap` mark.  Let's do something when we click on each square.  We can do this with a `click-select` interaction.  

In [32]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here!

# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

Ok fine, but our selection isn't linked to anything! Lets check out what heat_map selected actually is before we decide to do something with it:

In [33]:
heat_map.selected
#  note if I select a different box & re-run this cell,
#  I get out different values

array([[5, 2]])

So the *trait* of the heat_map that gets updated when we select a box is the x/y indicies.

Let's start simple: write a little function that links the data value to the selected & lets print this in a little ipywidgets label:

In [34]:
mySelectedLabel = ipywidgets.Label()

Let's now define what happens to this label when our heatmap is selected.  If we recall back to when we started learning about ipywidgets and traitlets, this will be a change in the `mySelectedLabel` widget's *value* when a *trait* of our `GridHeatMap` object changes.

First, let's define this action, starting simple: just print out whatever is selected:

In [35]:
def on_selected(change):
    print(change)

Now, let's re-construct our heatmap and link this `on_selected` function to the *trait* of the selected heatmap:

In [36]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

{'name': 'selected', 'old': None, 'new': array([[5, 2]]), 'owner': GridHeatMap(anchor_style={'fill': 'blue'}, color=array([[0.65771209, 0.86892101, 0.75079741, 0.47831359, 0.26155098,
        0.52151869, 0.27907678, 0.53829732, 0.33304627, 0.023503  ],
       [0.88353795, 0.41370045, 0.45037387, 0.25472344, 0.26821432,
        0.44175616, 0.29519296, 0.95435813, 0.7924018 , 0.88556012],
       [0.6459481 , 0.5365875 , 0.24092927, 0.59133017, 0.31490256,
        0.96413999, 0.17960387, 0.26897582, 0.33230235, 0.53189301],
       [0.51955953, 0.79508841, 0.56310568, 0.14217045, 0.98689766,
        0.53832668, 0.8374997 , 0.43176806, 0.04720695, 0.68010954],
       [0.04892631, 0.7190729 , 0.03472731, 0.05751688, 0.53299076,
        0.25977685, 0.14191432, 0.02961739, 0.06236137, 0.1124625 ],
       [0.40157269, 0.38420189, 0.09597065, 0.71033088, 0.51774316,
        0.84195228, 0.7285728 , 0.43345603, 0.90410568, 0.24502789],
       [0.10461881, 0.10283937, 0.30794282, 0.29275377, 0.8532

So, we can see that what gets printed out when we select is a dictionary -- this is like a "change" dictionary with an ipywidget that we played with last week and it has some familiar things in it like the `old` and `new` keys, the `owner` key, etc.  

Check out the `selected=array...` in the above -- this is how we can grab the index of whatever grid we have selected.

It also is storing a lot of information about our `GridHeatMap` plot!  

Since the change "owner" is our heat_map marks, let's print these out so we can access the indicies.  Once we do this, we can then use these indicies to access the data in our plot.  

One thing at a time though - let's just print out the selected indicies:

In [37]:
def on_selected(change):
    print(change['owner'].selected)

In [38]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

[[7 2]]
[[4 2]]


It turns out we can actually `SHIFT-select` and select a selection of boxes at one time.  Depending on your browser/OS you can also use `CMD` or `CTRL`-select to select individual boxes.  However, this is a little bit dependent on how your browser/trackpad/mouse is set up.

(`CMD`-select doesn't work in notebooks on my Mac, but it does in jupyter-lab.  Go fig.)

**DEMONSTRATE**

Because of this we actual `selected` set of indicies we want to access can be more than just x/y indicies - it can be an array of indicies representing all of the `SHIFT-select`ed points.

For the sake of simplicity, let's *only* do things when we select one point.  So we will *only* take out the first element of this selected array.  Let's print this with our `on_selected` function:

In [39]:
def on_selected(change):
    if len(change['owner'].selected) == 1:
        print(change['owner'].selected[0])
    # else: don't update anything

In [40]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

[7 3]
[4 2]
[2 4]


Now you'll notice if I `SHIFT-select` I still only get the set of x/y indicies associated with the blue selected point.  Sweet.

Now that we have these indicies in our plot, we can (finally) update our Label widget to print out what the data value is at this point:

In [41]:
def on_selected(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j] # grab data value
        mySelectedLabel.value = 'Data Value = ' + str(v) # set our label

Now we just have to make sure we show both of the figure and the label when we display:

In [42]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])


# ADDED: putting widget and plot together
myDashboard = ipywidgets.VBox([mySelectedLabel, fig]) # have label on top of fig
myDashboard # show

Hey neat!  So now when we do an action, in this case selecting, on one object (the heat map) we have updates *tied to* another object, in this case we are also updating our label widget's value.

This is how we will build up dashboards that allow us to display different aspects of our data in linked views.

Let's practice one of these linked views now by making a linked histogram of a 3D dataset instead of printing the value with a 2D dataset.

## Random heatmap + Histogram with 3D data

Now let's move on to making a preliminary dashboard for multi-dimensional datasets. Let's first start with some randomly generated data again, this time in 3D:

In [43]:
data = np.random.random((10, 10,20))
data

array([[[0.65609098, 0.54849294, 0.66275366, ..., 0.16646674,
         0.25458291, 0.65165466],
        [0.37557578, 0.78087719, 0.71752335, ..., 0.65701462,
         0.08036759, 0.38405943],
        [0.75081362, 0.83218219, 0.55293578, ..., 0.27711716,
         0.16159428, 0.54331255],
        ...,
        [0.00699485, 0.52098847, 0.75893561, ..., 0.69167966,
         0.40022626, 0.86958999],
        [0.42062424, 0.04826411, 0.48615863, ..., 0.5175557 ,
         0.34743407, 0.79050742],
        [0.63873514, 0.00608346, 0.49834801, ..., 0.45243371,
         0.59574584, 0.35971594]],

       [[0.81421506, 0.1087619 , 0.13369648, ..., 0.46065003,
         0.67340832, 0.4711756 ],
        [0.41007004, 0.19519476, 0.23183482, ..., 0.16540756,
         0.45407939, 0.99006517],
        [0.08756718, 0.63431294, 0.51227171, ..., 0.62082677,
         0.01761658, 0.41732563],
        ...,
        [0.89258796, 0.00252644, 0.86137237, ..., 0.648207  ,
         0.56055958, 0.24806089],
        [0.4

In [44]:
data.shape

(10, 10, 20)

In [45]:
data[0,0,:]
# we can see that no instead of 1 value, each "i,j" component
#  has an array of values

array([0.65609098, 0.54849294, 0.66275366, 0.35296201, 0.4945217 ,
       0.01501054, 0.30824447, 0.76283386, 0.67482426, 0.39682069,
       0.13697038, 0.97446691, 0.64771791, 0.88199405, 0.73987346,
       0.71749855, 0.24462128, 0.16646674, 0.25458291, 0.65165466])

Make the heatmap plot like before.

First, scales and axis (x/y and color):

In [47]:
# Scales: now add scales - colors, x & y
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Axis: create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

Now, instead of feeding in `data` like we did in 2D for our heatmap, let's feed in the sum of data along the z-axis:

In [48]:
# Marks: lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = np.sum(data, axis=2),
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

Let's include our label in our dashboard:

In [49]:
# create label again
mySelectedLabel = ipywidgets.Label()

This time, let's have the data print out the sum along the z-axis instead of just a data value at an x/y index position:

In [50]:
def on_selected(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j].sum() # grab data value at x/y index and sum along z
        mySelectedLabel.value = 'Data Sum = ' + str(v) # set our label

Observe change:

In [51]:
heat_map.observe(on_selected, 'selected')

Combine and display:

In [52]:
fig = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])

myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

Ultimately what we want to do is select an x/y grid and then "expand" our data along z into a histogram such that if we select a grid on our heatmap a new histogram is generated that shows the distribution of values along z.  

Before we link these two things together, let's make a histogram of a single "z" value by fixing our x/y indicies:

In [53]:
i,j = 0,0 # can be any combo

In [54]:
data[i,j] # 20 elements

array([0.65609098, 0.54849294, 0.66275366, 0.35296201, 0.4945217 ,
       0.01501054, 0.30824447, 0.76283386, 0.67482426, 0.39682069,
       0.13697038, 0.97446691, 0.64771791, 0.88199405, 0.73987346,
       0.71749855, 0.24462128, 0.16646674, 0.25458291, 0.65165466])

Let's make a histogram.    

Let's think about what our x/y scales will be: we want to show the distribution of values along z.  Intuitavely, we know this will go between $\sim$0-1 since we have randomly generated values.

So, our "x" axis for this plot should be a linear scale so it can go from 0-1, and our "y" axis should be linear and will show the frequency of values in each bin.

Scales:

In [55]:
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

Let's make axis with these scales:

In [56]:
x_axh = bqplot.Axis(scale = x_sch, label = 'Value of 3rd axis')
y_axh = bqplot.Axis(scale = y_sch, 
                    orientation = 'vertical', 
                    label='Frequency')

Now we will use `bqplot.Hist` to make this histogram:

In [57]:
hist = bqplot.Hist(sample = data[i,j,:],
                   normalized = False, # normalized=False means we get counts in each bin
                   scales = {'sample': x_sch, 'count': y_sch}, # sample is data values, count is frequency
                   bins = 5) # number of bins

Note here that we specified this plot in a different way than the `GridHeatMap` and `Scatter` -- each type of `bqplot` plot has different parameters associated with the type of plot we are using.

In [58]:
figh = bqplot.Figure(marks = [hist], axes = [x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

Let's pause here and think about how to link up our histogram i,j with our selections on the heatmap.  First, what values of the histogram can we update?  Let's check:

In [59]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [60]:
hist.sample

array([0.65609098, 0.54849294, 0.66275366, 0.35296201, 0.4945217 ,
       0.01501054, 0.30824447, 0.76283386, 0.67482426, 0.39682069,
       0.13697038, 0.97446691, 0.64771791, 0.88199405, 0.73987346,
       0.71749855, 0.24462128, 0.16646674, 0.25458291, 0.65165466])

Hey!  Here is where our data values are stored!  Like with when we observe changes in our heat map and update the values of our ipywidget's value we want to also update this sample's data!  

Let's update our `on_selected` function to reflect this:

In [61]:
def on_selected(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j].sum() # grab data value at x/y index and sum along z
        mySelectedLabel.value = 'Data Sum = ' + str(v) # set our label
        # NOW ALSO: update our histogram
        hist.sample = data[i,j,:]

We don't have to go through the exersise of rebuilding our heatmap and histogram in general, but let's just do it for the sake of completeness and not accidentally re-linking thinks we shouldn't:

#1 heatmap:

In [62]:
# (1) Scales: x/y, colors
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# (2) Axis: x/y, colors
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# (3) Marks: heatmap
heat_map = bqplot.GridHeatMap(color = np.sum(data, axis=2),
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# (4) Link selection on heatmap to other things
heat_map.observe(on_selected, 'selected')

# (5) Paint heatmap canvas, don't display yet:
fig_heatmap = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])

#2 histogram:

In [63]:
# (1) scales: x/y, linear
x_sch = bqplot.LinearScale() # range of z-axis data
y_sch = bqplot.LinearScale() # frequency of z-axis data in bins

# (2) axis: x/y
x_axh = bqplot.Axis(scale = x_sch, label = 'Value of 3rd axis')
y_axh = bqplot.Axis(scale = y_sch, 
                    orientation = 'vertical', 
                    label='Frequency')

# (3) Marks: histogram - start with just 0,0 in i/j -- can do other place holders
hist = bqplot.Hist(sample = data[0,0,:],
                   normalized = False, # normalized=False means we get counts in each bin
                   scales = {'sample': x_sch, 'count': y_sch}, # sample is data values, count is frequency
                   bins = 5) # number of bins

# (4) NO LINKING ON HISTOGRAM SIDE

# (5) Paint histogram canvas, don't display yet
fig_hist = bqplot.Figure(marks = [hist], axes = [x_axh, y_axh])

Create dashboard layout and display:

In [64]:
# side by side figures
figures = ipywidgets.HBox([fig_heatmap, fig_hist])

# label on top
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

Ok close, but its all smooshed!  We can play with the layout of our plots before we display.  To do this we use some more CSS-like styling options, in particular, `layout`:

In [65]:
# mess with figure layout:
fig_heatmap.layout.min_width = '500px' # feel free to change for your screen
fig_hist.layout.min_width = '500px'

# side by side figures
figures = ipywidgets.HBox([fig_heatmap, fig_hist])

# label on top
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

Note that update was "back-reactive" in that it changed the figure layout above as well!  Super sweet!

#### Further complications: linking in different directions

We can also apply some other links to further enhance our dashboard.  One that we've messed with before is allowing the user to select the number of bins of a histogram.

There are a few ways to do this, but one "easier" way is to just link the histogram "bins" with the value of a bins-slider.  

If we recall: `bins` was another key that was listed in hist:

In [66]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [67]:
hist.bins = 5 # this changes the bins of our histogram above in a back-reactive way -- traitlets magic!

Let's add a little integer slider to allow our user to select the number of bins for the histogram:

In [68]:
bins_slider = ipywidgets.IntSlider(value=5, min=1, max=data.shape[2]) # don't make more bins than data points!

A reminder of what this looks like:

In [69]:
bins_slider

IntSlider(value=5, max=20, min=1)

We can use `link` or `jslink` to link the value of this slider to our histogram's number of bins:

In [70]:
ipywidgets.jslink((bins_slider, 'value'), (hist, 'bins'))

Link(source=(IntSlider(value=5, max=20, min=1), 'value'), target=(Hist(bins=5, colors=['steelblue'], count=arr…

While this change is "backreactive", let's redo our figure layout so we can see everything a bit better:

In [71]:
# mess with figure layout:
fig_heatmap.layout.min_width = '500px' # feel free to change for your screen
fig_hist.layout.min_width = '500px'

# side by side figures
figures = ipywidgets.HBox([fig_heatmap, fig_hist])

# label on top to the left, bins slider to the right
controls = ipywidgets.HBox([mySelectedLabel, bins_slider])

# combined
myDashboard = ipywidgets.VBox([controls, figures])
myDashboard

## Interactive plots with bqplot's matplotlib-like interface

There is a `matplotlib`-like interface in `bqplot` that we can also use to make interactive figures.

In [72]:
import bqplot.pyplot as bplt

We can start with our gridded heatmap:

In [73]:
# first let's set up a figure object - the call is a little different for bqplot
fig = bplt.figure(padding_y=0.0)

# we'll call plt's gridheatmap function
heat_map = bplt.gridheatmap(data[:,:,0]) # just take bottom part of data
fig

Figure(axes=[ColorAxis(scale=ColorScale()), Axis(orientation='vertical', scale=OrdinalScale(reverse=True)), Ax…

We can make our plots interactive in much the same way as before:

In [74]:
# same function as before:
def on_selected_bplt(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j].sum() # grab data value at x/y index and sum along z
        mySelectedLabel.value = 'Data Sum = ' + str(v) # set our label
        # NOW ALSO: update our histogram
        hist.sample = data[i,j,:]

In [77]:
mySelectedLabel = ipywidgets.Label()

In [78]:
fig = bplt.figure(padding_y=0.0) # set up a figure object
bplt.scales(scales={'color':bqplot.ColorScale(scheme='Reds')})

# use bqplot's plt interface to plot:
heat_map = bplt.gridheatmap(np.sum(data, axis=2),
                            interactions={'click':'select'}, 
                            anchor_style = {'fill':'blue'})

# hook heat_maps selected value to the label 
heat_map.observe(on_selected_bplt, 'selected')

# change labels
fig.axes[2].label = 'X' # xaxes label
fig.axes[1].label = 'Y' # yaxes label

# 0 is the colorbar axis
fig.axes[0].orientation = 'horizontal'
fig.axes[0].side = 'top' # vertical and side=right don't work rightnow?

# show both the fig and label in a vertical box
ipywidgets.VBox([mySelectedLabel,fig])

In [79]:
fig_hist = bplt.figure(padding_y=0.0) # set up a figure object

# use bqplot's plt interface to plot:
hist = bplt.hist(sample = data[0,0,:],
                   normalized = False, # normalized=False means we get counts in each bin
                   bins = 5) 

# change labels
fig_hist.axes[1].label = 'Z values' # xaxes label
fig_hist.axes[0].label = 'Frequency' # yaxes label

fig_hist # empty plot of x/y

Figure(axes=[Axis(label='Frequency', orientation='vertical', scale=LinearScale()), Axis(label='Z values', scal…

In [80]:
fig.layout.min_width='500px'
fig_hist.layout.min_width='500px'

ipywidgets.VBox([mySelectedLabel,
                 ipywidgets.HBox([fig,fig_hist])])

## Extras: Interactive histogramming with bqplot

Now, lets try some interactive histogramming of our buildings data:

In [81]:
import pandas as pd
buildings = pd.read_csv("/Users/jillnaiman/Downloads/building_inventory.csv",
                        na_values = {'Year Acquired': 0, 
                                     'Year Constructed': 0, 
                                     'Square Footage': 0})

Let's create some linear scales and attach axis like before:

In [82]:
# since buildings is our data, we don't have to do anything
#  with that, but we do need to create our scales and 
# axes like we've been doing before:
# (1)
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation = 'vertical')

# (2) now, lets do an interactive rebinning, but lets
# use bqplot and a slider widget to do it
hist = bqplot.Hist(sample = buildings["Year Acquired"],
            scales = {'sample': x_sc, 'count': y_sc},
                   bins = 128, normalized = True,
                   colors = ["#FFFFFF"])

# lets also create a slider like we've done before
islider = ipywidgets.IntSlider(min = 8, max = 128, step = 1)
# and lets link our sider and our bins of our histogram
ipywidgets.link((islider, 'value'), (hist, 'bins'))
# construct a fig
#fig = bqplot.Figure(marks = [hist], axes = [x_ax, y_ax])
# ***RUN NEXT CELL BEFORE ADDING 2ND HIST

# (3) ok, but maybe we want to see our original histogram
#  underneath, lets add this to our figure
hist2 = bqplot.Hist(sample = buildings["Year Acquired"],
                   opacity = 0.1, normalized = True,
            scales = {'sample': x_sc, 'count': y_sc},
                  bins = 128)
fig = bqplot.Figure(marks = [hist, hist2], axes = [x_ax, y_ax])

# for 2 & 3
#display(ipywidgets.VBox([fig, islider]))
ipywidgets.VBox([fig, islider])

## Extras: Wealth of Nations plot
* originially from the TedTalk: https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen
* found on Rosling's website: https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen
* We're going to make a tool similar to GapMinders:https://www.gapminder.org/world/
* Much of this is, in more detail, in the PyGothum-2017 github: https://github.com/dmadeka/PyGotham-2017 
* This will talk to javascript on the backend to mimic the output of another plotting package d3.js, but we don't have to learn about d3.js (just now) and can instead rely on our current Python knowledge

In [83]:
# import pandas if we have not
import pandas as pd

# lets start off our plot at the initial year of 1800
initial_year = 1800

In [84]:
# we'll read in our datafile and apply 
# some pre-written cleaning routines 
# get out the data we want for our plotting
from wealth_of_nations import process_data, get_min_max, get_data

# grab data
data = process_data('/Users/jillnaiman/Downloads/nations.json')

data

name               region  \
0          Angola   Sub-Saharan Africa   
1           Benin   Sub-Saharan Africa   
2        Botswana   Sub-Saharan Africa   
3    Burkina Faso   Sub-Saharan Africa   
4         Burundi   Sub-Saharan Africa   
..            ...                  ...   
174      Thailand  East Asia & Pacific   
175   Timor-Leste  East Asia & Pacific   
177         Tonga  East Asia & Pacific   
178       Vietnam  East Asia & Pacific   
179       Vanuatu  East Asia & Pacific   

                                                income  \
0    [359.93, 359.93, 359.93, 359.93, 359.93, 359.9...   
1    [553.72, 553.72, 553.72, 553.72, 553.72, 553.7...   
2    [407.36, 407.36, 407.36, 407.36, 407.36, 407.3...   
3    [454.33, 454.33, 454.33, 454.33, 454.33, 454.3...   
4    [447.59, 447.59, 447.59, 447.59, 447.59, 447.5...   
..                                                 ...   
174  [496.98, 496.98, 496.98, 496.98, 496.98, 496.9...   
175  [514.12, 514.3505, 514.581, 514.8115, 515.042,...   
177  [667.71, 667.71, 667.71, 667.71, 667.71, 667.7...   
178  [459.71, 459.71, 459.71, 459.71, 459.71, 459.7...   
179  [829.58, 829.58, 829.58, 829.58, 829.58, 829.5...   

                                            population  \
0    [1567028.0, 1567028.0, 1567028.0, 1567028.0, 1...   
1    [636559.0, 636559.0, 636559.0, 636559.0, 63655...   
2    [121000.0, 121000.0, 121000.0, 121000.0, 12100...   
3    [1665421.0, 1665421.0, 1665421.0, 1665421.0, 1...   
4    [899097.0, 899097.0, 899097.0, 899097.0, 89909...   
..                                                 ...   
174  [4665000.0, 4665000.0, 4665000.0, 4665000.0, 4...   
175  [137262.0, 137262.0, 137262.0, 137262.0, 13726...   
177  [18658.0, 18654.325581395347, 18650.6511627907...   
178  [6551000.0, 6551000.0, 6551000.0, 6551000.0, 6...   
179  [27791.0, 27791.0, 27791.0, 27791.0, 27791.0, ...   

                                        lifeExpectancy  
0    [26.98, 26.98, 26.98, 26.98, 26.98, 26.98, 26....  
1    [31.0, 31.0, 31.0, 31.0, 31.0, 31.0, 31.0, 31....  
2    [33.6, 33.6, 33.6, 33.6, 33.6, 33.6, 33.6, 33....  
3    [29.2, 29.2, 29.2, 29.2, 29.2, 29.2, 29.2, 29....  
4    [31.5, 31.5, 31.5, 31.5, 31.5, 31.5, 31.5, 31....  
..                                                 ...  
174  [30.4, 30.4, 30.4, 30.4, 30.4, 30.4, 30.4, 30....  
175  [28.97, 28.97, 28.97, 28.97, 28.97, 28.97, 28....  
177  [57.91, 57.91, 57.91, 57.91, 57.91, 57.91, 57....  
178  [32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32....  
179  [40.8, 40.8, 40.8, 40.8, 40.8, 40.8, 40.8, 40....  

[178 rows x 5 columns]

In [85]:
# grab min & max values of our variables of interest
income_min, income_max, life_exp_min, life_exp_max, pop_min, pop_max = get_min_max(data)

In [86]:
# lets allow for a mouse-over interaction
# for silly:
import bqplot
tt = bqplot.Tooltip(fields=['name', 'x', 'y'], 
                    labels=['Country Name', 
                            'Income per Capita', 'Life Expectancy'])
#bqplot.Tooltip?

In [87]:
# we will label what year is being plotted, just like in the Gabminder plot
year_label = bqplot.Label(x=[0.75], y=[0.10], 
                   font_size=52, font_weight='bolder', 
                   colors=['orange'],
                   text=[str(initial_year)], enable_move=True)

In [88]:
# we'll define our scales like before
# here we scale our x & y axis to the scales of the min and max of our data
x_sc = bqplot.LogScale(min=income_min, max=income_max)
y_sc = bqplot.LinearScale(min=life_exp_min, max=life_exp_max)

# this is just something to color-code each circle by the region it corresponds to
#  (for example, asia, south america, africa, etc)
# the colors call is just mapping each catagorical variable to a color
c_sc = bqplot.OrdinalColorScale(domain=data['region'].unique().tolist(), 
                                colors=bqplot.CATEGORY10[:6])

# finally, we want the size of each of our dots to correspond to the population of 
# each country
#size_sc = bqplot.LinearScale(min=pop_min, max=pop_max)#, mid_range=0.1)
size_sc = bqplot.LinearScale(max=1326856173.0, min=2128.0)
#bqplot.LinearScale?

In [89]:
# create and label our x & y axis
ax_y = bqplot.Axis(label='Life Expectancy', scale=y_sc, 
                   orientation='vertical', side='left', 
                   grid_lines='solid')
ax_x = bqplot.Axis(label='Income per Capita', scale=x_sc, 
                   grid_lines='solid')

In [90]:
# now we'll use another little function from our library above to grab
# data for our initial setup (year = 1800)
# Start with the first year's data
cap_income, life_exp, pop = get_data(data,initial_year,initial_year)

In [91]:
# now lets make our scatter plot!
wealth_scat = bqplot.Scatter(x=cap_income, y=life_exp, 
                             color=data['region'], size=pop,
                      names=data['name'], display_names=False,
                      scales={'x': x_sc, 'y': y_sc, 'color': c_sc, 
                              'size': size_sc},
                      default_size=4112, tooltip=tt, 
                             animate=True, stroke='Black',
                      unhovered_style={'opacity': 0.5})
# much of these calls are things we've seen before, others will allow fun things 
#  like animation and also the ability to click on our plot and interact with it

In [92]:
# for our initial, 1800 view, we'll just allow the first "line" of the evolution of the 
# each nation's track to be displayed... this is essentially a place holder (visible = false)
nation_line = bqplot.Lines(x=data['income'][0], 
                           y=data['lifeExpectancy'][0], 
                           colors=['Gray'],
                       scales={'x': x_sc, 'y': y_sc}, visible=False)

In [93]:
# milliseconds of time between changes we make
time_interval = 10

In [94]:
# create the figure & 
fig = bqplot.Figure(marks=[wealth_scat, year_label, nation_line], 
                    axes=[ax_x, ax_y],
             title='Health and Wealth of Nations', 
                    animation_duration=time_interval)

# lets control the size in pixels too
fig.layout.min_width = '960px'
fig.layout.min_height = '640px'

In [95]:
# we'll use our friend the int slider to slide through years
# for silly:
import ipywidgets
year_slider = ipywidgets.IntSlider(min=1800, max=2008, step=1, description='Year', value=initial_year)

In [96]:
# make sure we define what happens when we change the year on our slider
def year_changed(change):
    wealth_scat.x, wealth_scat.y, wealth_scat.size = get_data(data,year_slider.value,initial_year)
    #wealth_scat.size+=1000
    year_label.text = [str(year_slider.value)]

year_slider.observe(year_changed, 'value')

In [97]:
# now we'll say what happens when we hover over an object
# we'll use "change" again to make it such that if a 
# user hovers over a country, the countries "life line" 
#  is visible
def hover_changed(change):
    if change.new is not None:
        nation_line.x = data['income'][change.new + 1]
        nation_line.y = data['lifeExpectancy'][change.new + 1]
        nation_line.visible = True
    else:
        nation_line.visible = False
        
wealth_scat.observe(hover_changed, 'hovered_point')

In [98]:
# finally, lets add a little play button so we can animate
#  what happens in time, just like on the d3.js plot
play_button = ipywidgets.Play(min=1800, max=2008, interval=time_interval)
# note, we use "jslink" because the "backend" here is javascript
#  bqplot is just interacting with javascript
ipywidgets.jslink((play_button, 'value'), (year_slider, 'value'))

Link(source=(Play(value=1800, interval=10, max=2008, min=1800), 'value'), target=(IntSlider(value=1800, descri…

In [99]:
# finally, lets put it all together!!

ipywidgets.VBox([ipywidgets.HBox([play_button, year_slider]), fig])